name: flipmap
services:
  backend:
    image: ghcr.io/anti-computer-club/flipmap-backend:latest
    # Expected from .env interpolation
    environment: [ORS_API_KEY, FLIPMAP_BACKEND_IP, FLIPMAP_BACKEND_PORT]
    depends_on:
      - caddy

  caddy:
    image: ghcr.io/anti-computer-club/flipmap-caddy:latest
    restart: unless-stopped # I trust this more than the binary
    environment:
      # This gets passed into the Caddyfile
      SITE_ADDRESS: ${SITE_ADDRESS}
      APP_PORT: ${FLIPMAP_BACKEND_PORT}
      CADDY_ADMIN: 0.0.0.0:2019
    cap_add:
      # Supposedly improves QUIC perf
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      # This should never be exposed to the internet - but host might need it
      - "127.0.0.1:2019:2019"
    volumes:
      - caddy_data:/data
      - /srv/www:/srv/www:ro

volumes:
  # 'Not a Cache' purging will remove certs, OCSP staples, etc
  caddy_data:
